## Template CI SMG SegInf
include:
  - project: 'smg-code/templates/pipelines-seginf'
    ref: main
    file: 
      - '.sast-defectdojo.gitlab-ci.yml'

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "develop"