management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true