apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../../base"

namespace: afilmed-dev

images:
- name: IMAGE_VALUE
  newName: registry.swissmedical.com.ar/swissmedical/core-campanias:latest-dev
  
# MODIFICAR EL ARCHIVO './application.envs' PARA CONFIGURAR LAS VARIABLES DE ENTORNO
configMapGenerator:
- name: core-campanias-properties
  envs:
  - application.envs

