-- CREATE DATABASE IF NOT EXIST PAYROLL;

CREATE TABLE IF NOT EXISTS `EMPLOYEES`(
    `id`          INTEGER PRIMARY KEY AUTO_INCREMENT,
    `name`       VARCHAR(100) NOT NULL,
    `role`      VARCHAR(100) NOT NULL
);