kind: Service
apiVersion: v1
metadata:
  name: core-campanias
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
  selector:
    app: core-campanias
